# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          
      - name: Install Dependencies
        run: npm install
      
      - name: Run Test
        run: npm run test

  build-push:
    runs-on: ubuntu-latest
    env:
      GIT_DEPLOY_KEY: ${{secrets.CI_DEPLOY_KEY}}
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
      
    - name: Install Dependencies
      run: npm install

    - name: Run Build
      run: npm run build
    
    - name: Push to gh-pages
      run: |
        cd build/
        mkdir ~/.ssh
        ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts && \
        echo "${GIT_DEPLOY_KEY}" > ~/.ssh/id_rsa && \
        chmod 400 ~/.ssh/id_rsa
        git init && \
        git remote add deploy git@github.com:aman95/portfolio.git && \
        git checkout -b gh-pages && \
        git config user.name "${GITHUB_ACTOR}" && \
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
        git add . && \
        timestamp=$(date +%s%3N) && \
        git commit -m "Automated deployment to GitHub Pages on $timestamp" > /dev/null 2>&1 && \
        git push deploy gh-pages --force && \
        rm -fr .git && \
        rm -f ~/.ssh/id_rsa
